### ISSUE TITLE
运行proxy出现问题

### ISSUE THREAD

**Issue by jinghuashang** [Darknights-dev/Darknights-proxy#3]
PS C:\Users\******\Desktop\Darknights-server-nginx-ver\Darknights-proxy-main> python Darknights-proxy.py
Traceback (most recent call last):
  File "C:\Users\******\Desktop\Darknights-server-nginx-ver\Darknights-proxy-main\Darknights-proxy.py", line 2, in <module>
    from mitmproxy.proxy.config import ProxyConfig
ModuleNotFoundError: No module named 'mitmproxy.proxy.config'

**Comment by Darknights-master** [comment]
Versions mismatch. Mitmproxy 7.x or later does not support this syntax any more.
Try `pip install mitmproxy==6.0.2`
